// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADtv_q9QC_05IihM5cXFGI4mc_BXIVBZ0',
    appId: '1:809867489398:web:f1d9ab0108dc21f17c6f57',
    messagingSenderId: '809867489398',
    projectId: 'fitguide-tfc',
    authDomain: 'fitguide-tfc.firebaseapp.com',
    storageBucket: 'fitguide-tfc.firebasestorage.app',
    measurementId: 'G-FE0SYR638D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhtIM4VS53ExyTYtS7Xwa_BCrVeOM3P5A',
    appId: '1:809867489398:android:b073386262e50ce17c6f57',
    messagingSenderId: '809867489398',
    projectId: 'fitguide-tfc',
    storageBucket: 'fitguide-tfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1VrKFEzoLaS2-hRrfUBgUp4y5aqY9soo',
    appId: '1:809867489398:ios:a5803c4e2f62b21f7c6f57',
    messagingSenderId: '809867489398',
    projectId: 'fitguide-tfc',
    storageBucket: 'fitguide-tfc.firebasestorage.app',
    iosBundleId: 'com.example.tfcFitguide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1VrKFEzoLaS2-hRrfUBgUp4y5aqY9soo',
    appId: '1:809867489398:ios:a5803c4e2f62b21f7c6f57',
    messagingSenderId: '809867489398',
    projectId: 'fitguide-tfc',
    storageBucket: 'fitguide-tfc.firebasestorage.app',
    iosBundleId: 'com.example.tfcFitguide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADtv_q9QC_05IihM5cXFGI4mc_BXIVBZ0',
    appId: '1:809867489398:web:7fd1d792e90a2cad7c6f57',
    messagingSenderId: '809867489398',
    projectId: 'fitguide-tfc',
    authDomain: 'fitguide-tfc.firebaseapp.com',
    storageBucket: 'fitguide-tfc.firebasestorage.app',
    measurementId: 'G-DQQCDQNXRT',
  );
}
